djcrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace="leads"))
]

leads/urls.py
from django.urls import path
from .views import lead_delete, lead_detail, lead_list, lead_create, lead_update

app_name = "leads"

urlpatterns = [
    path('', lead_list, name='lead-list'),
    path('create/', lead_create, name='lead-create'),
    path('<int:pk>/', lead_detail, name='lead-detail'),
    path('<int:pk>/update/', lead_update, name='lead-update'),
    path('<int:pk>/delete/', lead_delete, name='lead-delete'),
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import CASCADE


class User(AbstractUser):
    pass


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey("Agent", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

leads/forms.py
from django import forms
from .models import Lead

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
        )

class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)

leads/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Agent, Lead
from .forms import LeadForm, LeadModelForm


def lead_list(request):
    leads = Lead.objects.all()
    context = { "leads": leads }
    return render(request, "leads/lead_list.html", context)


def lead_detail(request, pk):
    lead = Lead.objects.get(id=pk)
    context = { "lead": lead }
    return render(request, "leads/lead_detail.html", context)


def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        "form": form
    }
    return render(request, "leads/lead_create.html", context)


def lead_update(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == "POST":
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = { 
        "form": form,
        "lead": lead
    }
    return render(request, "leads/lead_update.html", context)


def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads")

leads/templates/leads/home_page.html
{% extends "base.html" %}
{% block content %}
    <p>Leads in the database</p>
    <ul>
        {% for lead in leads %}
            <li>{{ lead }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

leads/templates/leads/lead_create.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <title>Lead create</title>
    <style>
      .lead {
        padding-top: 10px;
        padding-bottom: 10px;
        padding-left: 6px;
        padding-right: 6px;
        margin-top: 10px;
        background-color: #f6f6f6;
        width: 100%;
      }
    </style>
  </head>
  <body>
  <a href="/leads">Go back to leads</a>
  <hr />
    <h1>Create a new lead</h1>
    <div class="lead"> 
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
      </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
  </body>
</html>

leads/templates/leads/lead_detail.html
{% extends "base.html" %}
{% block content %}
  <a href="{% url 'leads:lead-list' %}">Go back to leads</a>
  <hr />
    <h1>Details of {{ lead.first_name }}</h1>
    <div class="lead">
      {{ lead.first_name }} {{ lead.last_name }}. Age: {{ lead.age }}, Agent: {{ lead.agent }}
    </div>
    <hr />
    <a href="{% url 'leads:lead-update' lead.pk %}"> Update this lead</a>
    <a href="{% url 'leads:lead-delete' lead.pk %}"> Delete this lead</a>
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}
{% block content %}
  <a href="{% url 'leads:lead-create' %}">Create a new Lead</a>
    <hr />
    <h1>Lead list</h1>
        {% for lead in leads %}
            <a href="{% url 'leads:lead-detail' lead.pk %}"><div class="lead">{{ lead.first_name }} {{ lead.last_name }}</a>. Age: {{ lead.age }}</div>
        {% endfor %}
    </ul>
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% block content %}
  <a href="{% url 'leads:lead-list' %}">Go back to leads</a>
  <hr />
    <h1>Update lead: {{ lead.first_name }} {{ lead.last_name }}</h1>
    <div class="lead"> 
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
      </form>
    </div>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <title>Lead list</title>
    <style>
      .lead {
        padding-top: 10px;
        padding-bottom: 10px;
        padding-left: 6px;
        padding-right: 6px;
        margin-top: 10px;
        background-color: #f6f6f6;
        width: 100%;
      }
    </style>
  </head>
  <body>
    {% block content %}

    {% endblock content %}

    {% include "scripts.html" %}
    
  </body>
</html>

templates/scripts.html
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>